In [ ]:
 #install fuzzywuzzy
!pip install fuzzywuzzy
!pip install openpyxl

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

import fuzzywuzzy as fw
from fuzzywuzzy import process
import openpyxl as op

/home/tarun/.local/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [4]:
# odisha
df1 = pd.read_excel('India_AC_shapefile.xlsx')
df1.head()
# read sheet 2 of goa masterlist
df2 = pd.read_excel('tamilnadu _masterllist.xlsx', sheet_name=0)
# df2 = pd.read_excel('goa_masterlist.xlsx')
df2.rename(columns={'Cleaned': 'cleaned'}, inplace=True)
df2.rename(columns={'assembly constituency': 'AC_NAME'}, inplace=True)
df2.rename(columns={'file status ': 'File Status'}, inplace=True)
df2.rename(columns={'Error comment': 'Error Comment'}, inplace=True)
df2.rename(columns={'year': 'year'}, inplace=True)

df2.head()



def find_fuzzy_match(name, choices):
    if not name:
        return None
    result = process.extractOne(name, choices)
    if result:
        return result[0]
    else:
        return None

# Create a mapping dictionary for rows in df2
ac_name_mapping = {row['AC_NAME']: row for idx, row in df2.iterrows()}

# Filter df1 for rows with ST_NAME "GOA" and map columns from df2 based on fuzzy matching
df1_state = df1[df1['ST_NAME'] == 'TAMIL NADU'].copy()  # Filter rows where ST_NAME is "ODISHA"
print(df1_state)
df1_state['Downloaded'] = df1_state['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df2['AC_NAME'])]['Downloaded'])
df1_state['year'] = df1_state['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df2['AC_NAME'])]['year'])
df1_state['Converted'] = df1_state['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df2['AC_NAME'])]['Converted'])
df1_state['cleaned'] = df1_state['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df2['AC_NAME'])]['cleaned'])
df1_state['File Status'] = df1_state['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df2['AC_NAME'])]['File Status'])
df1_state['Error Comment'] = df1_state['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df2['AC_NAME'])]['Error Comment'])
df1_state['election'] = df1_state['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df2['AC_NAME'])]['election'])


df1_state.to_excel('TAMIL NADU vs 2021.xlsx', index=False)

/home/tarun/.local/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

       FID  OBJECTID  ST_CODE     ST_NAME  DT_CODE      DIST_NAME  AC_NO  \
441    441         1       33  TAMIL NADU        1    THIRUVALLUR      2
442    442         7       33  TAMIL NADU        1    THIRUVALLUR      3
443    443         1       33  TAMIL NADU        1    THIRUVALLUR      4
444    444         1       33  TAMIL NADU        1    THIRUVALLUR      1
445    445         1       33  TAMIL NADU        1    THIRUVALLUR      5
...    ...       ...      ...         ...      ...            ...    ...
670    670        38       33  TAMIL NADU       29    TIRUNELVELI    228
671    671        39       33  TAMIL NADU       30  KANNIYAKUMARI    234
672    672        39       33  TAMIL NADU       30  KANNIYAKUMARI    231
673    673        39       33  TAMIL NADU       30  KANNIYAKUMARI    230
4181  4181        29       33  TAMIL NADU       20     THIRUVARUR    169

               AC_NAME  PC_NO            PC_NAME  PC_ID STATUS  Shape_Leng  \
441       Ponneri (SC)      1    TIRUVALLUR (SC)   3301           1.386232
442          Tiruttani      7          ARAKKONAM   3307           2.257739
443        Thiruvallur      1    TIRUVALLUR (SC)   3301           2.365738
444      Gummidipoondi      1    TIRUVALLUR (SC)   3301           2.231660
445   Poonamallee (SC)      1    TIRUVALLUR (SC)   3301           1.541052
...                ...    ...                ...    ...    ...         ...
670         Radhapuram     38        TIRUNELVELI   3338           1.775416
671          Killiyoor     39      KANNIYAKUMARI   3339           0.571264
672           Colachel     39      KANNIYAKUMARI   3339           0.803291
673          Nagercoil     39      KANNIYAKUMARI   3339           0.517745
4181          Nannilam     29  NAGAPATTINAM (SC)   3329           1.453697

      Shape_Area
441     0.049620
442     0.049243
443     0.055022
444     0.065783
445     0.027693
...          ...
670     0.077476
671     0.010222
672     0.012611
673     0.008629
4181    0.033369

[234 rows x 14 columns]

In [5]:
# odisha
df1 = pd.read_excel('India_AC_shapefile.xlsx')
df1.head()
# read sheet 2 of goa masterlist
df2 = pd.read_excel('tamilnadu _masterllist.xlsx', sheet_name=1)
# df2 = pd.read_excel('goa_masterlist.xlsx')
df2.rename(columns={'Cleaned': 'cleaned'}, inplace=True)
df2.rename(columns={'assembly constituency': 'AC_NAME'}, inplace=True)
df2.rename(columns={'File Status ': 'File Status'}, inplace=True)
df2.rename(columns={'Error comment': 'Error Comment'}, inplace=True)
df2.rename(columns={'year': 'year'}, inplace=True)

df2.head()



def find_fuzzy_match(name, choices):
    if not name:
        return None
    result = process.extractOne(name, choices)
    if result:
        return result[0]
    else:
        return None

# Create a mapping dictionary for rows in df2
ac_name_mapping = {row['AC_NAME']: row for idx, row in df2.iterrows()}

# Filter df1 for rows with ST_NAME "GOA" and map columns from df2 based on fuzzy matching
df1_state = df1[df1['ST_NAME'] == 'TAMIL NADU'].copy()  # Filter rows where ST_NAME is "ODISHA"
print(df1_state)
df1_state['Downloaded'] = df1_state['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df2['AC_NAME'])]['Downloaded'])
df1_state['year'] = df1_state['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df2['AC_NAME'])]['year'])
df1_state['Converted'] = df1_state['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df2['AC_NAME'])]['Converted'])
df1_state['cleaned'] = df1_state['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df2['AC_NAME'])]['cleaned'])
df1_state['File Status'] = df1_state['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df2['AC_NAME'])]['File Status'])
df1_state['Error Comment'] = df1_state['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df2['AC_NAME'])]['Error Comment'])
df1_state['election'] = df1_state['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df2['AC_NAME'])]['election'])
# df1_state['Interim'] = df1_state['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df2['AC_NAME'])]['Interim'])
# df1_state['Note'] = df1_state['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df2['AC_NAME'])]['Note'])


df1_state.to_excel('TAMIL NADU vs 2016.xlsx', index=False)

/home/tarun/.local/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

       FID  OBJECTID  ST_CODE     ST_NAME  DT_CODE      DIST_NAME  AC_NO  \
441    441         1       33  TAMIL NADU        1    THIRUVALLUR      2
442    442         7       33  TAMIL NADU        1    THIRUVALLUR      3
443    443         1       33  TAMIL NADU        1    THIRUVALLUR      4
444    444         1       33  TAMIL NADU        1    THIRUVALLUR      1
445    445         1       33  TAMIL NADU        1    THIRUVALLUR      5
...    ...       ...      ...         ...      ...            ...    ...
670    670        38       33  TAMIL NADU       29    TIRUNELVELI    228
671    671        39       33  TAMIL NADU       30  KANNIYAKUMARI    234
672    672        39       33  TAMIL NADU       30  KANNIYAKUMARI    231
673    673        39       33  TAMIL NADU       30  KANNIYAKUMARI    230
4181  4181        29       33  TAMIL NADU       20     THIRUVARUR    169

               AC_NAME  PC_NO            PC_NAME  PC_ID STATUS  Shape_Leng  \
441       Ponneri (SC)      1    TIRUVALLUR (SC)   3301           1.386232
442          Tiruttani      7          ARAKKONAM   3307           2.257739
443        Thiruvallur      1    TIRUVALLUR (SC)   3301           2.365738
444      Gummidipoondi      1    TIRUVALLUR (SC)   3301           2.231660
445   Poonamallee (SC)      1    TIRUVALLUR (SC)   3301           1.541052
...                ...    ...                ...    ...    ...         ...
670         Radhapuram     38        TIRUNELVELI   3338           1.775416
671          Killiyoor     39      KANNIYAKUMARI   3339           0.571264
672           Colachel     39      KANNIYAKUMARI   3339           0.803291
673          Nagercoil     39      KANNIYAKUMARI   3339           0.517745
4181          Nannilam     29  NAGAPATTINAM (SC)   3329           1.453697

      Shape_Area
441     0.049620
442     0.049243
443     0.055022
444     0.065783
445     0.027693
...          ...
670     0.077476
671     0.010222
672     0.012611
673     0.008629
4181    0.033369

[234 rows x 14 columns]

In [6]:
# goa for bye-election 
df1 = pd.read_excel('India_AC_shapefile.xlsx')
df1.head()
# read sheet 2 of goa masterlist
df2 = pd.read_excel('tamilnadu _masterllist.xlsx', sheet_name=2)
df2.rename(columns={'constituency': 'AC_NAME'}, inplace=True)

# df2 = pd.read_excel('goa_masterlist.xlsx')
df2.head()
print(df2)


def find_fuzzy_match(name, choices):
    if not name:
        return None
    result = process.extractOne(name, choices)
    if result:
        return result[0]
    else:
        return None

# Create a mapping dictionary for rows in df2
ac_name_mapping = {row['AC_NAME']: row for idx, row in df1.iterrows()}

# Filter df1 for rows with ST_NAME "GOA" and map columns from df2 based on fuzzy matching
df1_state = df1[df1['ST_NAME'] == 'TAMIL NADU'].copy()  # Filter rows where ST_NAME is "GOA"
print(df1_state)




df2['FID'] = df2['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df1_state['AC_NAME'])]['FID'])
df2['OBJECTID'] = df2['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df1_state['AC_NAME'])]['OBJECTID'])
df2['ST_CODE'] = df2['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df1_state['AC_NAME'])]['ST_CODE'])
df2['ST_NAME'] = df2['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df1_state['AC_NAME'])]['ST_NAME'])
df2['DT_CODE'] = df2['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df1_state['AC_NAME'])]['DT_CODE'])
df2['DIST_NAME'] = df2['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df1_state['AC_NAME'])]['DIST_NAME'])
df2['AC_NO'] = df2['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df1_state['AC_NAME'])]['AC_NO'])
df2['PC_NO'] = df2['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df1_state['AC_NAME'])]['PC_NO'])
df2['PC_NAME'] = df2['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df1_state['AC_NAME'])]['PC_NAME'])
df2['PC_ID'] = df2['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df1_state['AC_NAME'])]['PC_ID'])
df2['STATUS'] = df2['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df1_state['AC_NAME'])]['STATUS'])
df2['Shape_Leng'] = df2['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df1_state['AC_NAME'])]['Shape_Leng'])
df2['Shape_Area'] = df2['AC_NAME'].apply(lambda x: ac_name_mapping[find_fuzzy_match(x, df1_state['AC_NAME'])]['Shape_Area'])

# drop AC no
df2.drop(['Ac.no'], axis=1, inplace=True)
df2.drop(['state'], axis=1, inplace=True)

# print(df1)
df2.to_excel('TAMIL NADU bye.xlsx', index=False)

/home/tarun/.local/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

    year  election       state  Ac.no             AC_NAME  Downloaded  \
0    2016    VS_be  Tamil Nadu    134        Aravakurichi           1
1    2016    VS_be  Tamil Nadu    174           Thanjavur           1
2    2016    VS_be  Tamil Nadu    195   Thiruparankundram           1
3    2017    VS_be  Tamil Nadu     11            RK Nagar           1
4    2019    VS_be  Tamil Nadu      5         poonamallee           1
5    2019    VS_be  Tamil Nadu     12            Perambur           1
6    2019    VS_be  Tamil Nadu     33          Thiruporur           1
7    2019    VS_be  Tamil Nadu     39          Sholinghur           1
8    2019    VS_be  Tamil Nadu     46     Gudiyatham (SC)           1
9    2019    VS_be  Tamil Nadu     48               Ambur           1
10   2019    VS_be  Tamil Nadu     55               Hosur           1
11   2019    VS_be  Tamil Nadu     60     Pappireddipatti           1
12   2019    VS_be  Tamil Nadu     61          Harur (SC)           1
13   2019    VS_be  Tamil Nadu    130     Nilakottai (SC)           1
14   2019    VS_be  Tamil Nadu    168           Tiruvarur           1
15   2019    VS_be  Tamil Nadu    174           Thanjavur           1
16   2019    VS_be  Tamil Nadu    187    Manamadurai (SC)           1
17   2019    VS_be  Tamil Nadu    198           Andipatti           1
18   2019    VS_be  Tamil Nadu    199    Periyakulam (SC)           1
19   2019    VS_be  Tamil Nadu    204              Sattur           1
20   2019    VS_be  Tamil Nadu    209     Paramakudi (SC)           1
21   2019    VS_be  Tamil Nadu    213        Vilathikulam           1
22   2019    VS_be  Tamil Nadu    134        Aravakurichi           1
23   2019    VS_be  Tamil Nadu    116               Sulur           1
24   2019    VS_be  Tamil Nadu    195  Thirupparankundram           1
25   2019    VS_be  Tamil Nadu    217         Ottapidaram           1
26   2019    VS_be  Tamil Nadu     75          Vikravandi           1
27   2019    VS_be  Tamil Nadu    227           Nanguneri           1
28   2023    VS_be  Tamil Nadu     98          Erode East           1

    Converted  Cleaned               file status         Comment
0           0        0  Downloaded and Converted      Image File
1           1        1              File Cleaned  Data available
2           1        1              File Cleaned  Data available
3           1        1              File Cleaned  Data available
4           1        1              File Cleaned  Data available
5           1        1              File Cleaned  Data available
6           1        1              File Cleaned  Data available
7           1        1              File Cleaned  Data available
8           1        1              File Cleaned  Data available
9           1        1              File Cleaned  Data available
10          1        1              File Cleaned  Data available
11          1        1              File Cleaned  Data available
12          1        1              File Cleaned  Data available
13          1        1              File Cleaned  Data available
14          1        1              File Cleaned  Data available
15          1        1              File Cleaned  Data available
16          1        1              File Cleaned  Data available
17          1        1              File Cleaned  Data available
18          1        1              File Cleaned  Data available
19          1        1              File Cleaned  Data available
20          1        1              File Cleaned  Data available
21          1        1              File Cleaned  Data available
22          1        1              File Cleaned  Data available
23          1        1              File Cleaned  Data available
24          1        1              File Cleaned  Data available
25          1        1              File Cleaned  Data available
26          0        0  Downloaded and Converted      Image File
27          0        0  Downloaded and Converted      Image File
28          0        0  Downloaded and Converted      Image File
       FID  OBJECTID  ST_CODE     ST_NAME  DT_CODE      DIST_NAME  AC_NO  \
441    441         1       33  TAMIL NADU        1    THIRUVALLUR      2
442    442         7       33  TAMIL NADU        1    THIRUVALLUR      3
443    443         1       33  TAMIL NADU        1    THIRUVALLUR      4
444    444         1       33  TAMIL NADU        1    THIRUVALLUR      1
445    445         1       33  TAMIL NADU        1    THIRUVALLUR      5
...    ...       ...      ...         ...      ...            ...    ...
670    670        38       33  TAMIL NADU       29    TIRUNELVELI    228
671    671        39       33  TAMIL NADU       30  KANNIYAKUMARI    234
672    672        39       33  TAMIL NADU       30  KANNIYAKUMARI    231
673    673        39       33  TAMIL NADU       30  KANNIYAKUMARI    230
4181  4181        29       33  TAMIL NADU       20     THIRUVARUR    169

               AC_NAME  PC_NO            PC_NAME  PC_ID STATUS  Shape_Leng  \
441       Ponneri (SC)      1    TIRUVALLUR (SC)   3301           1.386232
442          Tiruttani      7          ARAKKONAM   3307           2.257739
443        Thiruvallur      1    TIRUVALLUR (SC)   3301           2.365738
444      Gummidipoondi      1    TIRUVALLUR (SC)   3301           2.231660
445   Poonamallee (SC)      1    TIRUVALLUR (SC)   3301           1.541052
...                ...    ...                ...    ...    ...         ...
670         Radhapuram     38        TIRUNELVELI   3338           1.775416
671          Killiyoor     39      KANNIYAKUMARI   3339           0.571264
672           Colachel     39      KANNIYAKUMARI   3339           0.803291
673          Nagercoil     39      KANNIYAKUMARI   3339           0.517745
4181          Nannilam     29  NAGAPATTINAM (SC)   3329           1.453697

      Shape_Area
441     0.049620
442     0.049243
443     0.055022
444     0.065783
445     0.027693
...          ...
670     0.077476
671     0.010222
672     0.012611
673     0.008629
4181    0.033369

[234 rows x 14 columns]